# Generated by Django 4.0.4 on 2022-04-20 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='firstapp/premiumproductimages')),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'permissions': (('can_see_command_premuin', 'can see command for premium delivery on premium products'), ('can_add_premium_discount', 'can avail more premium discount on premium products')),
            },
        ),
    ]
